### ISSUE TITLE
Error installing through the node-red palette

### ISSUE THREAD

**Issue by TinajaLabs** [mapero/node-red-contrib-smartplug#14]
Error: Command failed: npm install --production node-red-contrib-smartplug
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git+https://github.com/mwittig/node-http-digest-client.git#b8551fe1a27e364d87b90f6a22117232f7683f71 resetting remote /home/pi/.npm/_git-remotes/git-https-github-com-mwittig-node-http-digest-client...

On raspberry pi with raspbian jesse

**Comment by mapero** [comment]
Is git installed and in your PATH?

**Comment by TinajaLabs** [comment]
@mapero,  
All other installs through the palette have worked so far on this server.  Git is installed.  This eve I will check that there's no problem with access to github.

Thanks for your help.

**Comment by TinajaLabs** [comment]
OK.  Git was not installed on that server after all.  I've added it to my ansible baseline playbook so all my servers will get it by default.  Thanks for your help.
