### ISSUE TITLE
Produces error every second when plug cannot be reached

### ISSUE THREAD

**Issue by TotallyInformation** [mapero/node-red-contrib-smartplug#8]
Please, please, please! Don't continuously raise errors when the plug cannot be reached! There is no need, a single error is enough, then give up for a bit before trying again. Better, respect the timeout and retry values so we don't get logs filled with rubbish.

**Comment by mapero** [comment]
I will look into it. The input node should already respect the retry value, so is assume you mean the output node?

**Comment by JonMurphy** [comment]
Jochen - Here are the errors I get from the smartplug-in node.  And the bottom set of errors goes on forever.  I think this is what Julian is referring to.

Here is the **error** output with SmartPlug unplugged:

``` text
May 22, 2016 at 10:39:38 AM CDT  EdiPlug
msg : error
Error: Request timeout occurred - request aborted

May 22, 2016 at 10:39:53 AM CDT  EdiPlug
msg : error
Error: Request timeout occurred - request aborted

May 22, 2016 at 10:40:08 AM CDT  EdiPlug
msg : error
Error: Request timeout occurred - request aborted
```

The above continues every 15 seconds (8 messages total) lasting ~2 minutes.
.

Here is the **error** output with SmartPlug unplugged longer than 2 minutes:

``` text
May 22, 2016 at 10:41:31 AM CDT  EdiPlug
msg : error
Error: connect EHOSTUNREACH

May 22, 2016 at 10:41:39 AM CDT  EdiPlug
msg : error
Error: connect EHOSTUNREACH

May 22, 2016 at 10:41:47 AM CDT  EdiPlug
msg : error
Error: connect EHOSTUNREACH
```

The above continues every 8 seconds forever or until the SmartPlug is plugged into an outlet.

**Comment by mapero** [comment]
I will look into it, maybe tomorrow. I wonder why the time interval changes between different error messages.
Did you increase the retry time interval?

**Comment by JonMurphy** [comment]
Jochen - I tried changing the Interval (ms)

![screen shot 2016-06-07 at 11 00 35 am_thumb](https://cloud.githubusercontent.com/assets/15616372/15865150/417bbd22-2c9f-11e6-8512-fd9af1fde50b.png)

I could not find "retry time interval" and I am assume "Timeout" is the same.  What exactly does "Timeout" and "Retry(s)" do?

![screen shot 2016-06-07 at 11 06 06 am_thumb](https://cloud.githubusercontent.com/assets/15616372/15865420/4550bbd6-2ca0-11e6-8863-c82d4961d751.png)

**Comment by JonMurphy** [comment]
Jochen - I changed the Timeout from 10 to 60.  This changed the amount and duration of the **Error: Request timeout occurred - request aborted** messages.  I only received one of those.  But the **Error: connect EHOSTUNREACH** still happen every 8 seconds and go on forever.

![screen shot 2016-06-07 at 11 16 20 am_thumb](https://cloud.githubusercontent.com/assets/15616372/15865799/c4a93d76-2ca1-11e6-84f7-9e6ab9a9bf7e.png)

**Comment by TotallyInformation** [comment]
Thanks for the commit, sorry I didn't have time this week to take part in the conversation. I'll try the updated version.

**Comment by JonMurphy** [comment]
Jochen - I installed the current version.  I really like the Node status added to the Node - very helpful!  

After I installed the new version I found the smartplug node did not work properly.  I kept getting errors like this:
![screen shot 2016-06-10 at 11 51 42 am copy_thumb](https://cloud.githubusercontent.com/assets/15616372/15972508/7c719b92-2f04-11e6-93e8-5b607e27a56b.png)

Finally I received an error similar to this (sorry no pic of the exact error):
![screen shot 2016-06-10 at 11 59 35 am_thumb](https://cloud.githubusercontent.com/assets/15616372/15972539/a772562e-2f04-11e6-9e73-0fba136e323f.png)

A node-red restart did not help.  I deleted the smartplug nodes (in & out) in my flow, deployed the flow as-is, then re-added the smartplug nodes.  That allowed me to move forward.  Still testing!

Jon

**Comment by TotallyInformation** [comment]
I've now updated and retested. I can confirm that I no longer get the repeating error, many thanks for the rapid fix.

**Comment by JonMurphy** [comment]
Jochen - I figured out the Timeout and Heartbeat.  But what does Discovery = Scanned do?

Small picky item - if the EdiPlug sends data during the Init period (before Connected), then the data that returns looks like this:
![screen shot 2016-06-10 at 4 26 14 pm copy_thumb](https://cloud.githubusercontent.com/assets/15616372/15979525/1be592f8-2f2a-11e6-8c2a-0835a47b2d7a.png)

Also repeating error is gone!  Thank you!    Jon

**Comment by JonMurphy** [comment]
forgot one important item - I am still getting this error when clicking the Deploy:
![screen shot 2016-06-10 at 11 51 42 am copy_thumb](https://cloud.githubusercontent.com/assets/15616372/15979840/3de903b0-2f2c-11e6-9f1c-b3b8cbcb38c8.png)

**Comment by mapero** [comment]
I will look into it. Thanks for the feedback.
